name: aplikasi_reservasi_dokter_candra_safitri
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  carousel_slider: ^4.2.1
  dio: ^5.3.2
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_tts: ^3.8.5
  get: ^4.6.6
  google_fonts: ^6.1.0
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  meta: ^1.9.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: assets/app_splash_screen_android_12.png
  branding: assets/app_branding_android_11.png
  android_12:
    image: assets/app_splash_screen_android_12.png
    color: "#ffffff"
    branding: assets/app_branding_android_12_coba.png
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images_onboarding/
